# Generated by Django 3.2.6 on 2021-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoinersite', '0002_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coin',
            name='vote',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='launch_date',
            field=models.DateField(verbose_name=''),
        ),
    ]
