# Generated by Django 3.2.6 on 2021-08-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoinersite', '0004_auto_20210826_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
