# Generated by Django 3.2.6 on 2021-08-26 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptocoinersite', '0005_alter_coin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='CoinVoter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('coin_status', models.BooleanField(default=False)),
                ('coinid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cryptocoinersite.coin')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
