# Generated by Django 3.2.6 on 2021-08-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoinersite', '0006_auto_20210826_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='h1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='h24',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
