# Generated by Django 3.2.6 on 2021-08-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoinersite', '0008_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
