# Generated by Django 3.2.6 on 2021-08-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoinersite', '0011_alter_coin_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='launch_date',
            field=models.DateField(default=None, verbose_name=''),
        ),
    ]
