# Generated by Django 3.2.6 on 2021-08-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoinersite', '0013_alter_coin_launch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='', upload_to='site/images'),
        ),
    ]
